name: CMake

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:


  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: arm-none-eabi-gcc
    
      run: sudo apt-get install -y gcc-arm-none-eabi


    - name: mkdir
      run: mkdir ./build
    - name: Build
      # Build your program with the given configuration
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ./ -B ./build

    - name: publish
      uses: actions/upload-artifact@v2
      with:
        name: myapp-and-doc
        path: |
          ./build/timer.elf
          ./build/timer.bin
          ./build/timer.hex

